# Dockerfile-resizer
FROM python:3.9-slim

WORKDIR /app

COPY image_resizer_api/image_resizer_api.py /app
COPY requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5001

CMD ["python", "image_resizer_api.py"]