# Dockerfile-circular
FROM python:3.9-slim

WORKDIR /app

COPY circular_segmentation/circular_segmentation.py /app
COPY requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "circular_segmentation.py"]